<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<packaging>jar</packaging>
		<version>0.0.1</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>JavaWebApp</artifactId>
	<version>1.0-SNAPSHOT</version>
	<name>JavaWebApp</name>
	<description>JavaWebApp project for Spring Boot</description>

	<properties>
		<java.version>1.8</java.version>
	    <sonar.host.url>http://3.88.207.213:9000/</sonar.host.url>
        <sonar.login>squ_83a23a0a983992ec1d954e6b2f23a2fc2c1eb59b</sonar.login> 
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<!--plugin>
   				<groupId>org.apache.maven.plugins</groupId>
   				<artifactId>maven-deploy-plugin</artifactId>
   				<version>${maven-deploy-plugin.version}</version>
   			</plugin-->
		</plugins>
	</build>

	<distributionManagement>
    <snapshotRepository>
      <id>nexusdeploymentrepo</id>
	  <name>icici4-Snapshot Nexus Repository</name>
      <url>http://54.208.130.205:8081/repository/icici4-Snapshot/</url> <!-- Update the IP/Address to Your Nexus VM IP -->
    </snapshotRepository>											  <!-- Mmake sure to create the "maven-snapshots" repo in Nexus -->
	<repository>
	  <id>nexusdeploymentrepo</id>
	  <name>icici4-Release Nexus Repository</name>
      <url>http://54.208.130.205:8081/repository/icici4-Release/</url> <!-- Update the IP/Address to Your Nexus VM IP -->
    </repository>													 <!-- Also make sure you have the above two or one repositories created -->
  
  </distributionManagement>

</project>
